"""Emit LaTeX endpoint tables from post-fix metrics.json (no CSV round-trip).

tables/{mol}/endpoint_grid.csv is append-only and interleaves campaigns, so the
tables are built straight from results/*/U_*/<method>/<cost>/metrics.json and a
point is used only if it carries the post-fix keys.

    python scripts/plot/make_endpoint_tables.py --packing irrep
"""

from __future__ import annotations

import argparse
import glob
from json import JSONDecoder
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
METHODS = ("mixed_overlap", "mixed_disjoint", "iterative")
MOL_TEX = {"h2o": r"\mathrm{H_2O}", "n2": r"\mathrm{N_2}"}


def load_stream(path):
    text = Path(path).read_text()
    dec, i, obj = JSONDecoder(), 0, None
    while i < len(text):
        while i < len(text) and text[i].isspace():
            i += 1
        if i >= len(text):
            break
        obj, i = dec.raw_decode(text, i)
    return obj


def sci(x, digits=1):
    if x is None:
        return "--"
    x = abs(float(x))
    if x == 0:
        return "0"
    from math import floor, log10
    e = int(floor(log10(x)))
    m = x / 10 ** e
    return f"${m:.{digits}f}\\times10^{{{e}}}$"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--packing", default="irrep", choices=("irrep", "full"))
    ap.add_argument("-o", "--output", default=None)
    args = ap.parse_args()

    data = {}
    for f in glob.glob(str(REPO / f"results/*_endpoint_grid/bond_*/U_{args.packing}/*/*/metrics.json")):
        p = Path(f).parts
        d = load_stream(f)
        if d is None or ("reference_weight_ok" not in d and "exact_sector_source" not in d):
            continue
        mol = p[-6].split("_")[0]
        bond = round(float(p[-5].replace("bond_", "").replace("p", ".")), 4)
        data[(mol, bond, p[-3], p[-2])] = d

    out = [f"% generated by scripts/plot/make_endpoint_tables.py "
           f"--packing {args.packing}", ""]
    for mol in ("h2o", "n2"):
        for cost in ("NC", "variance"):
            bonds = sorted({k[1] for k in data if k[0] == mol and k[3] == cost})
            if not bonds:
                continue
            lab = f"tab:{mol}-{cost.lower()}-irrep"
            out += [
                r"\begin{table}[htbp]", r"\centering",
                rf"\caption{{${MOL_TEX[mol]}$ {cost} endpoints "
                rf"(geometry-derived PG exact, $U=\mathrm{{{args.packing}}}$): "
                rf"$K$, retained dim, sectors, $|\Delta E_{{\mathrm{{dec}}}}|$. "
                rf"All points converged with $\sum w_{{\mathrm{{ref}}}}=1$.}}",
                rf"\label{{{lab}}}",
                r"\resizebox{\textwidth}{!}{%",
                r"\begin{tabular}{c ccc ccc ccc}", r"\toprule",
                r"$R$ & \multicolumn{3}{c}{Mixed overlap} & "
                r"\multicolumn{3}{c}{Mixed disjoint} & \multicolumn{3}{c}{Iterative} \\",
                r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}\cmidrule(lr){8-10}",
                r" & $K$ & dim & $|\Delta E|$ & $K$ & dim & $|\Delta E|$ "
                r"& $K$ & dim & $|\Delta E|$ \\",
                r"\midrule",
            ]
            for b in bonds:
                cells = []
                for me in METHODS:
                    d = data.get((mol, b, me, cost))
                    if d is None:
                        cells += ["--", "--", "--"]
                        continue
                    star = "" if d.get("converged") else r"$^{\dagger}$"
                    cells += [f"{d.get('K')}{star}",
                              str(d.get("relevant_sectors_total_dim")),
                              sci(d.get("dE"))]
                out.append(f"{b:g} & " + " & ".join(cells) + r" \\")
            dmax = next((data[k].get("D_max") for k in data if k[0] == mol), None)
            out += [
                r"\bottomrule", r"\end{tabular}}",
                rf"\\[2pt]\footnotesize $D_{{\max}}={dmax}$ at every geometry, "
                rf"method and cost: with $r+M=N$ the largest retained sector is "
                rf"always the seniority-zero block $\binom{{n}}{{n_\alpha}}$.",
                r"\end{table}", "",
            ]

    path = Path(args.output or
                REPO / "tables" / "analysis" /
                f"endpoint_{args.packing}_tables.tex")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(out))
    print(f"[tex] {path.relative_to(REPO)}  ({len(data)} points)")


if __name__ == "__main__":
    main()
