"""Find approximate quasisymmetries for a given Hamiltonian and save their parameters."""

import argparse
from itertools import combinations
import numpy as np
import time
import ffsim
import scipy
import pyscf
from typing import Tuple, Callable

def callback(intermediate_result):
    print(intermediate_result.fun)
    print(time.strftime("%a, %d %b %Y %H:%M:%S", time.localtime()))

def commutator_cost_fci(moldata: ffsim.MolecularData) -> Callable:
    h_linop = ffsim.linear_operator(moldata.hamiltonian,
                                    norb=moldata.norb,
                                    nelec=moldata.nelec)
    fci_energy, fci_state = scipy.sparse.linalg.eigsh(h_linop, which="SA", k=1)

    iu = np.triu_indices(moldata.norb, k=1)

    def f(x):
        a = np.sin(x[-2]) * np.cos(x[-1])
        b = np.sin(x[-2]) * np.sin(x[-1])
        c = np.cos(x[-2])
        ops = []
        for i in range(moldata.norb):
            op = ffsim.FermionOperator(
                {
                    (ffsim.cre_a(i), ffsim.des_a(i)): a,
                    (ffsim.cre_b(i), ffsim.des_b(i)): b,
                    (ffsim.cre_a(i), ffsim.des_a(i), ffsim.cre_b(i), ffsim.des_b(i)): c
                }
            )
            ops.append(op)
        linops = [ffsim.linear_operator(op, moldata.norb, moldata.nelec) for op in ops]
        rotation_generator = np.zeros((moldata.norb, moldata.norb))
        rotation_generator[iu] = x[:-2]
        rotation_generator -= rotation_generator.T
        U = scipy.linalg.expm(rotation_generator)
        rotated_psi = ffsim.apply_orbital_rotation(fci_state, U, moldata.norb, moldata.nelec)
        states_after_s_i = [linop @ rotated_psi for linop in linops]
        unrotated_states = [ffsim.apply_orbital_rotation(psi, U.T.conj(), moldata.norb, moldata.nelec)
                            for psi in states_after_s_i]
        final_states = [h_linop @ psi - fci_energy * psi for psi in unrotated_states]
        return np.sum([np.linalg.norm(psi) ** 2 for psi in final_states])

    # xdim = iu[0].shape[0] + 2

    return f


if __name__=="__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("molpath",
                        help="path to the Hamiltonian (hdf5 generated by openfermion)")
    parser.add_argument("initialguesses",
                        help="path to file with initial guesses (one line = one point)")
    parser.add_argument("cost_function", help="what to optimize over")
    parser.add_argument("--verbose", action="store_true")
    parser.add_argument("--reference",
                        help="reference state to use in calculations (default: fci)",
                        default="fci")

    args = parser.parse_args()

    mol = pyscf.lib.chkfile.load_mol(args.molpath)
    mf = pyscf.scf.RHF(mol)
    mf.update_from_chk(args.molpath)

    moldata = ffsim.MolecularData.from_scf(mf)

    xs_filename = (time.strftime("%Y%m%d_%H%M%S", time.localtime())
                   + "_x_opt.txt")
    with open(xs_filename,
              "a", newline="") as fp:
        fp.write(str(vars(args)) + "\n")

    if args.cost_function == "commutator":
        f = commutator_cost_fci(moldata)
    else:
        raise NotImplementedError()


    initial_guesses = np.loadtxt(args.initialguesses)
    n_points = initial_guesses.shape[0]
    for i in range(n_points):
        x_0 = initial_guesses[i, :]
        print("x0", x_0)
        res = scipy.optimize.minimize(f, x_0,
                                      method="L-BFGS-B",
                                      options={"maxiter": 100},
                                      callback=callback if args.verbose else None)
        print(res.message)
        with open(xs_filename, "ab") as fp:
            np.savetxt(fp, res.x.reshape(1, res.x.shape[0]))

